# Generated by Django 5.2.4 on 2026-02-12 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerphone',
            name='phone',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
