databases:
  - name: mobile_store_DB
    plan: free

services:
  - type: web
    name: mobile_store
    runtime: python
    plan: free

    buildCommand: "./build.sh"

    startCommand: "gunicorn mobile_store.asgi:application -k uvicorn.workers.UvicornWorker"

    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mobile_store_DB
          property: connectionString

      - key: SECRET_KEY
        generateValue: true

      - key: WEB_CONCURRENCY
        value: 4